"""The growth cycle's `TrainingFn`, bound to the production trainer.

PR #166 merged the growth system with its trainer seam exercised only against
tiny local fakes. A fake trainer cannot demonstrate project validation, budget
enforcement, registry lifecycle, contamination binding, worker source identity,
or independent evaluation. This module tests the *binding* -- the thing that
turns the merged framework into authority to train.

The nine acceptance properties are the contract
(``docs/GROWTH_TRAINFN_BINDING_PLAN_2026-09-16.md``); the layers below mirror
its proof ladder:

* the **contract** layer (S0) proves the cycle seam itself, which had no
  coverage at all: a fake ``TrainingFn`` drives Model N -> promotion end to end;
* the **refusal** layer proves properties 2, 4, 5 and 9 hold *before* compute.
  Each refusal is asserted to have started no training subprocess -- a refusal
  that already ran the trainer is not a refusal;
* the **real** layer (S1-S6) drives a genuine tiny Qwen3 MoE through actual
  ``chowder project-validate`` and ``chowder train`` processes and requires the
  resulting rows to be terminal in the production registry.

The real layer needs torch/transformers, so it is gated the way the router
project suite is: it runs in the real-ML job, where a silent skip shows up in
the skip count.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import Any, Mapping, Sequence

import pytest

SRC = Path(__file__).resolve().parents[1] / "src"

from chowder.backend_selection import ROUTER_HEALING_ENGINE
from chowder.growth.capability import ALL_SKILLS, CapabilityProfile, SkillEstimate
from chowder.growth.contamination import ContaminationFirewall
from chowder.growth.curriculum import CurriculumEngine, CurriculumItem
from chowder.growth.cycle import CycleConfig, GrowthCycle
from chowder.growth.data_registry import DataRegistry, DataSource, admit
from chowder.growth.failure_bank import FailureBank
from chowder.growth.frontier_reference import SnapshotStore
from chowder.evals.result import MEASURED_PARENT, MEASURED_THIS_GENERATION
from chowder.growth.lineage import GenerationLedger, RegressionMemory
from chowder.growth.promotion import BenchmarkResult
from chowder.growth.recipe_planner import TrainingRecipe
from chowder.growth.training_binding import (
    STATUS_REFUSED,
    STATUS_SUCCEEDED,
    GrowthBindingError,
    GrowthEnvelope,
    SubprocessOutcome,
    SubprocessTrainingFn,
    default_runner,
)

TARGET = ALL_SKILLS[0]
PROTECTED = ALL_SKILLS[1]
BROAD = ALL_SKILLS[2]

TARGET_ID = "gsm8k@1.0"
PROTECTED_ID = "mmlu@2.0"
BROAD_ID = "arc@1.0"


# --------------------------------------------------------------------------
# shared fixtures and helpers
# --------------------------------------------------------------------------


def _envelope(**overrides: Any) -> GrowthEnvelope:
    values: dict[str, Any] = {
        "device_gpu_hours_ceiling": 1.0,
        "wall_gpu_hours_ceiling": 4.0,
        "project_gpu_hour_budget": 1.0,
    }
    values.update(overrides)
    return GrowthEnvelope(**values)


def _source(source_id: str = "src-1", **overrides: Any) -> DataSource:
    values: dict[str, Any] = {
        "source_id": source_id,
        "dataset_name": "tiny-synthetic",
        "revision": "abc123",
        "url": "https://example.invalid/tiny",
        "license": "CC-BY-4.0",
        "permitted_training_use": True,
        "domain": "synthetic",
        "language": "en",
        "source_type": "synthetic",
        "verification": "symbolic_numeric",
        "trust_class": "GOLD",
        "example_count": 500,
        "token_estimate": 10000,
        "provenance": "generated by the growth qualification ladder",
        "acquisition_timestamp": "2026-09-16T00:00:00Z",
        "source_hash": "0" * 64,
        "contamination_relationship": "CLEAN",
        "quality_score": 0.9,
        "pii_reviewed": True,
        "secrets_reviewed": True,
    }
    values.update(overrides)
    return DataSource(**values)


def _material(items: Sequence[CurriculumItem]) -> dict[str, list[str]]:
    return {
        item.item_id: [
            f"the router selects expert {index % 4} for token number {index} here"
            for index in range(40)
        ]
        for item in items
    }


def _recipe(*, recipe_id: str = "recipe-00", max_steps: int = 4, seq_len: int = 16,
            learning_rate: float = 0.05, item_ids: Sequence[str] = ()) -> TrainingRecipe:
    """A bounded recipe built directly, not through the planner.

    The planner always proposes ``seq_len`` 2048 for a real model; the ladder
    needs a 16-token tiny model. The planner's probe/kill conditions are covered
    by their own tests, and the binding's contract is "given a recipe, execute
    it" -- so the ladder supplies the recipe and lets the binding do the rest.
    """
    return TrainingRecipe(
        recipe_id=recipe_id,
        curriculum_item_ids=tuple(item_ids),
        mixture={"TARGET": 0.6, "PRESERVE": 0.2, "REPLAY": 0.2},
        learning_rate=learning_rate,
        scheduler="constant",
        warmup_steps=0,
        lora_rank=8,
        lora_alpha=16,
        target_modules=("q_proj", "v_proj"),
        seq_len=seq_len,
        batch_size=2,
        gradient_accumulation=1,
        max_steps=max_steps,
        objective="sft",
        replay_rate=0.2,
        dataset_manifest={"items": list(item_ids)},
        projected_device_gpu_hours=0.01,
        projected_wall_gpu_hours=0.035,
    )


def _items(version: str = "gen0", count: int = 2) -> tuple[CurriculumItem, ...]:
    engine = CurriculumEngine()
    profile = CapabilityProfile(
        model_version=version,
        raw_scores={TARGET_ID: 0.25},
        skills=tuple(
            SkillEstimate(skill=skill, estimate=0.25, confidence=0.9, evidence=(TARGET_ID,))
            for skill in ALL_SKILLS
        ),
    )
    return engine.plan(
        model_version=version,
        profile=profile,
        protected_sets=(PROTECTED_ID,),
        max_items=count,
        budget_examples=1000,
    )


def _cycle(tmp_path: Path, train_fn) -> GrowthCycle:
    return GrowthCycle(
        CycleConfig(
            cycle_id="cycle-000",
            parent_version="gen0",
            candidate_version="gen1",
            device_gpu_hours_ceiling=1.0,
            target_benchmarks=(TARGET_ID,),
            protected_benchmarks=(PROTECTED_ID,),
            broad_battery=(BROAD_ID,),
            recipe_count=2,
        ),
        curriculum=CurriculumEngine(),
        planner=_NullPlanner(),
        failure_bank=FailureBank(),
        firewall=ContaminationFirewall(),
        ledger=GenerationLedger(tmp_path / "ledger"),
        regression_memory=RegressionMemory(tmp_path / "probes"),
        snapshots=SnapshotStore(tmp_path / "snapshots"),
        train_fn=train_fn,
    )


class _NullPlanner:
    """The cycle's recipe phase is not what S0 is proving; the fake supplies none."""

    def propose(self, items, *, count: int = 4):  # noqa: ANN001, ARG002
        return ()


# --------------------------------------------------------------------------
# S0 -- the cycle seam itself
# --------------------------------------------------------------------------


def test_s0_a_fake_training_fn_drives_the_cycle_to_a_recorded_promotion(tmp_path: Path):
    """S0: the joined cycle runs Model N -> decision -> ledger with no gaps.

    The merged framework shipped this seam with no coverage at all, so the
    binding's positive control is that the seam it plugs into actually works:
    curriculum -> recipes -> training evidence -> predeclared promotion ->
    lineage record.
    """
    calls: list[str] = []

    def fake_train(recipe, items):  # noqa: ANN001
        calls.append(recipe.recipe_id)
        evidence = tmp_path / f"{recipe.recipe_id}-evidence.json"
        evidence.write_text(json.dumps({"recipe_id": recipe.recipe_id}), encoding="utf-8")
        return {
            "status": "SUCCEEDED",
            "measured_gpu_hours": 0.02,
            "evidence_path": str(evidence),
            "worst_expert_fraction": 0.0,
        }

    cycle = _cycle(tmp_path, fake_train)
    profile = CapabilityProfile(
        model_version="gen0",
        raw_scores={TARGET_ID: 0.25},
        skills=tuple(
            SkillEstimate(skill=s, estimate=0.25, confidence=0.9, evidence=(TARGET_ID,))
            for s in ALL_SKILLS
        ),
    )
    items = cycle.plan_curriculum(profile)
    assert items, "the curriculum phase must produce items for a measured profile"

    recipes = (_recipe(item_ids=[i.item_id for i in items]),)
    results = cycle.train_candidates(items, recipes)
    assert calls == ["recipe-00"]
    assert results[0]["recipe_id"] == "recipe-00"

    def _samples(mean: float) -> tuple[float, ...]:
        # Real spread: the promotion rule is a statistical test, and a constant
        # sample cannot be called significant without inventing variance.
        return (mean - 0.03,) * 3 + (mean + 0.03,) * 3

    def _measured(score: float, other: float, *, origin: str) -> dict[str, BenchmarkResult]:
        return {
            TARGET_ID: BenchmarkResult(
                benchmark_qualified_id=TARGET_ID,
                score=score,
                samples=_samples(score),
                contamination="CLEAN",
                measurement_origin=origin,
            ),
            PROTECTED_ID: BenchmarkResult(
                benchmark_qualified_id=PROTECTED_ID,
                score=other,
                samples=_samples(other),
                contamination="CLEAN",
                measurement_origin=origin,
            ),
            BROAD_ID: BenchmarkResult(
                benchmark_qualified_id=BROAD_ID,
                score=other,
                samples=_samples(other),
                contamination="CLEAN",
                measurement_origin=origin,
            ),
        }

    decision = cycle.decide_promotion(
        candidate_results=_measured(0.62, 0.80, origin=MEASURED_THIS_GENERATION),
        parent_results=_measured(0.30, 0.80, origin=MEASURED_PARENT),
        device_gpu_hours=results[0]["measured_gpu_hours"],
    )
    assert decision.verdict == "PROMOTED", decision.reasons

    outcome = cycle.finalize(
        decision,
        base_model={"path": "F:/llm-models/tiny", "manifest_sha256": "0" * 64},
        dataset_manifest_ref=str(tmp_path / "dataset.json"),
        curriculum_manifest_ref=str(tmp_path / "curriculum.json"),
        recipe=recipes[0].to_dict(),
        training_evidence_ref=results[0]["evidence_path"],
        evaluation_report_ref=str(tmp_path / "eval-report.json"),
    )
    assert outcome.verdict == "PROMOTED"
    assert [p.phase for p in outcome.phases] == ["promotion"]
    assert cycle.ledger.get("gen1").parent_version == "gen0"
    assert cycle.ledger.get("gen1").training_evidence_ref == results[0]["evidence_path"]


# --------------------------------------------------------------------------
# the refusal layer -- everything here must refuse *before* any compute
# --------------------------------------------------------------------------


class _RecordingRunner:
    """A runner that records commands and fakes a terminal, clean production run.

    It reads the same ``project.json`` the real CLI reads, so the registry rows,
    artifact and declared identity land where production would put them -- the
    binding's assertions are then about the binding, not about a fixture's idea
    of where things go.
    """

    def __init__(self, *, validate_returncode: int = 0, print_summary: bool = True,
                 create_registry_rows: bool = True, write_identity: bool = True,
                 artifact: bool = True, gpu_hours: float = 0.02,
                 device_gpu_hours: float | None = None) -> None:
        self.commands: list[tuple[str, ...]] = []
        self.validate_returncode = validate_returncode
        self.print_summary = print_summary
        self.create_registry_rows = create_registry_rows
        self.write_identity = write_identity
        self.artifact = artifact
        #: Wall-charged cost this fake run reports, the way the trainer does.
        self.gpu_hours = gpu_hours
        #: Device time, reported only when a run actually separates it. None
        #: models the trainer's ordinary summary, which reports wall only.
        self.device_gpu_hours = device_gpu_hours

    def __call__(self, command, cwd, environment, timeout):  # noqa: ANN001, ARG002
        self.commands.append(tuple(command))
        verb = command[-2] if len(command) >= 2 else ""
        if verb == "project-validate":
            return SubprocessOutcome(
                command=tuple(command),
                returncode=self.validate_returncode,
                stdout=json.dumps({"ok": True}) if self.validate_returncode == 0 else "",
                stderr="" if self.validate_returncode == 0 else "invalid configuration",
                seconds=0.01,
                timed_out=False,
            )
        project = json.loads((Path(cwd) / "project.json").read_text(encoding="utf-8"))
        experiment_id = project["experiment"]["experiment_id"]
        artifact_ref = self._write_run(Path(cwd), project) if self.create_registry_rows else None
        stdout = ""
        if self.print_summary:
            summary: dict[str, Any] = {
                "project": "growth-binding",
                "experiment_id": experiment_id,
                "succeeded": True,
                "promoted_experiment_id": None,
                "artifact_ref": artifact_ref,
                "metrics": {"holdout_loss": 0.5},
                "gpu_hours": self.gpu_hours,
                "error": None,
            }
            if self.device_gpu_hours is not None:
                summary["device_gpu_hours"] = self.device_gpu_hours
            stdout = "event: started\n" + json.dumps(
                summary, indent=2, sort_keys=True
            )
        return SubprocessOutcome(
            command=tuple(command), returncode=0, stdout=stdout, stderr="",
            seconds=1.0, timed_out=False,
        )

    def _write_run(self, cwd: Path, project: Mapping[str, Any]) -> str | None:
        sys.path.insert(0, str(SRC))
        from chowder.models import Experiment, ExperimentResult, Hypothesis
        from chowder.registry import RunRegistry

        experiment_id = project["experiment"]["experiment_id"]
        work_dir = Path(project["work_dir"])
        artifact = work_dir / "artifact"
        artifact.mkdir(parents=True, exist_ok=True)
        if self.artifact:
            (artifact / "payload.safetensors").write_bytes(b"payload")
            (artifact / "router_payload.json").write_text(
                json.dumps({"steps_completed": 4}), encoding="utf-8"
            )
        if self.write_identity:
            (work_dir / "chowder-identity.json").write_text(
                json.dumps(_identity_of_this_process()), encoding="utf-8"
            )
        registry = RunRegistry(Path(project["registry_path"]))
        try:
            registry.record_experiment(
                Experiment(
                    experiment_id=experiment_id,
                    parent_id=None,
                    hypothesis=Hypothesis(
                        observation="o", suspected_cause="c", intervention="i"
                    ),
                    config_patch={},
                    estimated_gpu_hours=0.1,
                )
            )
            registry.record_result(
                ExperimentResult(
                    experiment_id=experiment_id,
                    metrics={"holdout_loss": 0.5},
                    gpu_hours=self.gpu_hours,
                    artifact_ref=str(artifact),
                    evidence=(
                        {}
                        if self.device_gpu_hours is None
                        else {"device_gpu_hours": self.device_gpu_hours}
                    ),
                )
            )
            registry.update_experiment_status(experiment_id, "passed")
        finally:
            registry.close()
        return str(artifact) if self.artifact else None


def _identity_of_this_process() -> dict[str, Any]:
    sys.path.insert(0, str(SRC))
    from chowder.worker_env import chowder_source_identity

    return chowder_source_identity()


def _binding(tmp_path: Path, *, runner, registry: DataRegistry | None = None,
             firewall: ContaminationFirewall | None = None,
             material: Mapping[str, Sequence[str]] | None = None,
             template: Mapping[str, Any] | None = None, items=None,
             sources: Mapping[str, str] | None = None,
             envelope: GrowthEnvelope | None = None,
             registry_path: Path | None = None,
             attempt_files: Mapping[str, Sequence[str]] | None = None) -> SubprocessTrainingFn:
    items = items if items is not None else _items()
    item_ids = [item.item_id for item in items]
    return SubprocessTrainingFn(
        run_root=tmp_path / "attempts",
        project_template=template if template is not None else _template(tmp_path),
        registry_path=registry_path,
        envelope=envelope or _envelope(),
        registry=registry if registry is not None else _admitted_registry(),
        firewall=firewall if firewall is not None else ContaminationFirewall(),
        sources=sources or {item_id: "src-1" for item_id in item_ids},
        material=material if material is not None else _material(items),
        attempt_files=attempt_files,
        runner=runner,
        python=sys.executable,
    )


def _admitted_registry() -> DataRegistry:
    registry = DataRegistry()
    registry.register(admit(_source("src-1"), decision="included", reason="qualified"))
    return registry


def _template(tmp_path: Path, **overrides: Any) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "schema_version": 1,
        "name": "growth-binding",
        "seed": 1,
        "goal": {
            "metrics": [{"name": "holdout_loss", "direction": "minimize"}],
            "gpu_hour_budget": 1.0,
            "max_parallel_candidates": 1,
            "minimum_promotion_gain": 0.0,
        },
        "baseline": {"mode": "auto"},
        "experiment": {
            "experiment_id": "growth-ladder",
            "estimated_gpu_hours": 0.1,
            "hypothesis": {
                "observation": "the router gates are untrained",
                "suspected_cause": "the base was never adapted to this corpus",
                "intervention": "train mlp.gate.weight with the experts frozen",
            },
        },
        "config": {
            "backend": {
                "type": ROUTER_HEALING_ENGINE,
                "router_healing": {
                    "base_model_dir": str(tmp_path / "base"),
                    "corpus_path": "{corpus}",
                    "holdout_corpus_path": str(tmp_path / "holdout.txt"),
                    "max_steps": 4,
                    "learning_rate": 0.05,
                    "seq_len": 16,
                    "batch_size": 2,
                    "seed": 1,
                },
            },
            "evaluation": {"type": ROUTER_HEALING_ENGINE, "eval_batches": 2},
            "goal_lifecycle": {"mode": "legacy_unbounded"},
        },
    }
    payload.update(overrides)
    return payload


def test_the_binding_materializes_declared_attempt_files_before_validate(tmp_path: Path):
    """A template may reference auxiliary files (e.g. an evaluation split at a
    fixed absolute path). The binding writes them into the fresh attempt dir
    before project-validate -- the window where production refuses a missing
    evaluation dataset -- and records their content digests in the evidence."""
    runner = _RecordingRunner()
    binding = _binding(
        tmp_path,
        runner=runner,
        attempt_files={"eval.jsonl": ["{\"prompt\": \"p\", \"expected\": \"e\"}"], "notes.txt": ["hello"]},
    )
    evidence = dict(binding(_recipe(), _items()))
    assert evidence["status"] == "SUCCEEDED"
    attempt_dir = Path(evidence["attempt_dir"])
    eval_path = attempt_dir / "eval.jsonl"
    assert eval_path.exists()
    assert "prompt" in eval_path.read_text(encoding="utf-8")
    assert (attempt_dir / "notes.txt").read_text(encoding="utf-8").strip() == "hello"
    files = evidence["attempt_files"]
    assert set(files) == {"eval.jsonl", "notes.txt"}
    assert files["eval.jsonl"]["lines"] == 1
    assert len(files["eval.jsonl"]["sha256"]) == 64


def test_the_binding_refuses_attempt_files_outside_the_attempt_dir(tmp_path: Path):
    runner = _RecordingRunner()
    binding = _binding(
        tmp_path,
        runner=runner,
        attempt_files={"nested/eval.jsonl": ["x"]},
    )
    evidence = dict(binding(_recipe(), _items()))
    assert evidence["status"] == "REFUSED"
    assert evidence["refused_by"] == "template-contract"
    assert "directly in the attempt directory" in evidence["refusal_reason"]


def test_the_binding_refuses_a_recipe_over_the_growth_envelope(tmp_path: Path):
    """Property 4: the envelope is enforced by the binding, not just recorded."""
    runner = _RecordingRunner()
    binding = _binding(
        tmp_path,
        runner=runner,
        envelope=_envelope(device_gpu_hours_ceiling=0.001),
    )
    items = _items()
    evidence = binding(
        _recipe(item_ids=[i.item_id for i in items], max_steps=100_000), items
    )

    assert evidence["status"] == "REFUSED"
    assert evidence["refused_by"] == "growth-envelope"
    assert "device_gpu_hours_ceiling" in evidence["refusal_reason"]
    assert evidence["train_started"] is False
    assert runner.commands == [], f"a refused recipe ran a subprocess: {runner.commands}"


def test_the_binding_refuses_a_source_the_data_registry_has_not_admitted(tmp_path: Path):
    """Property 5: only admitted sources may supply material."""
    registry = DataRegistry()
    registry.register(_source("src-1"))  # registered, but still quarantine/pending
    runner = _RecordingRunner()
    binding = _binding(tmp_path, runner=runner, registry=registry)
    items = _items()

    evidence = binding(_recipe(item_ids=[i.item_id for i in items]), items)

    assert evidence["status"] == "REFUSED"
    assert evidence["refused_by"] == "data-registry"
    assert "not trainable" in evidence["refusal_reason"]
    assert runner.commands == []


def test_the_binding_refuses_protected_material_offered_as_training_text(tmp_path: Path):
    """Property 5: a contamination refusal is a refusal, not a warning."""
    protected_text = "what is the exact protected question number seven answer"
    firewall = ContaminationFirewall()
    firewall.register_protected(PROTECTED_ID, [protected_text])
    runner = _RecordingRunner()
    items = _items()
    material = _material(items)
    material[items[0].item_id] = [protected_text]

    binding = _binding(tmp_path, runner=runner, firewall=firewall, material=material)
    evidence = binding(_recipe(item_ids=[i.item_id for i in items]), items)

    assert evidence["status"] == "REFUSED"
    assert evidence["refused_by"] == "contamination-firewall"
    assert PROTECTED_ID in evidence["refusal_reason"] or "contaminat" in evidence["refusal_reason"]
    assert runner.commands == []


def test_the_binding_refuses_a_template_that_never_names_its_corpus(tmp_path: Path):
    """A template that names no corpus cannot be executed honestly: the binding
    cannot know which knob takes the text, and guessing would silently train on
    whatever the template already pointed at."""
    template = _template(tmp_path)
    del template["config"]["backend"]["router_healing"]["corpus_path"]
    runner = _RecordingRunner()
    binding = _binding(tmp_path, runner=runner, template=template)
    items = _items()

    evidence = binding(_recipe(item_ids=[i.item_id for i in items]), items)

    assert evidence["status"] == "REFUSED"
    assert evidence["refused_by"] == "template-contract"
    assert runner.commands == []


def test_the_binding_refuses_a_project_budget_looser_than_the_envelope(tmp_path: Path):
    """Property 4: the project ceiling is production's authority, so a template
    looser than the growth envelope is refused rather than silently clamped."""
    template = _template(tmp_path)
    template["goal"]["gpu_hour_budget"] = 50.0
    runner = _RecordingRunner()
    binding = _binding(tmp_path, runner=runner, template=template)
    items = _items()

    evidence = binding(_recipe(item_ids=[i.item_id for i in items]), items)

    assert evidence["status"] == "REFUSED"
    assert evidence["refused_by"] == "template-contract"
    assert "gpu_hour_budget" in evidence["refusal_reason"]
    assert runner.commands == []


def test_a_validation_refusal_never_starts_training(tmp_path: Path):
    """Property 2: the real validator refuses before any compute."""
    runner = _RecordingRunner(validate_returncode=1)
    binding = _binding(tmp_path, runner=runner)
    items = _items()

    evidence = binding(_recipe(item_ids=[i.item_id for i in items]), items)

    assert evidence["status"] == "REFUSED"
    assert evidence["refused_by"] == "project-validate"
    assert evidence["train_started"] is False
    verbs = [command[-2] for command in runner.commands]
    assert verbs == ["project-validate"], f"training ran despite a validation refusal: {verbs}"
    assert "invalid configuration" in Path(evidence["validate"]["stderr_ref"]).read_text(
        encoding="utf-8"
    )


def test_a_refused_recipe_leaves_durable_terminal_evidence(tmp_path: Path):
    """Property 9: refusals are evidence, and they are terminal."""
    runner = _RecordingRunner()
    binding = _binding(tmp_path, runner=runner, envelope=_envelope(device_gpu_hours_ceiling=0.0))
    items = _items()

    evidence = binding(_recipe(item_ids=[i.item_id for i in items]), items)

    assert evidence["status"] == "REFUSED"
    path = Path(evidence["evidence_path"])
    assert path.exists()
    recorded = json.loads(path.read_text(encoding="utf-8"))
    assert recorded["status"] == "REFUSED"
    assert recorded["refusal_reason"]
    assert Path(evidence["attempt_dir"]).exists()


def test_a_successful_train_that_overruns_its_wall_ceiling_settles_as_refused(tmp_path: Path):
    """Training succeeds, the frozen envelope does not: REFUSED.

    The pre-launch gate compares the recipe's *projection*; this test pins the
    post-run one, where the cost that actually happened decides. The train
    subprocess must have run (a refusal before compute is a different refusal),
    the artifact and every measurement must survive, and the reason must carry
    the machine-readable identifier rather than a prose note.
    """
    # Projection is 0.035 wall, so the ceiling admits the recipe; the run then
    # reports 0.08 wall for training plus 0.08 for its evaluation.
    runner = _RecordingRunner(gpu_hours=0.08)
    binding = _binding(tmp_path, runner=runner, envelope=_envelope(wall_gpu_hours_ceiling=0.05))
    items = _items()

    evidence = binding(_recipe(item_ids=[i.item_id for i in items]), items)

    assert evidence["train_started"] is True
    assert any(command[-2] == "train" for command in runner.commands)
    assert evidence["status"] == STATUS_REFUSED
    assert evidence["refused_by"] == "budget_settlement"
    assert evidence["measured_gpu_hours"] == pytest.approx(0.08)
    assert evidence["budget_settlement"]["budget_compliant"] is False
    assert any(
        "ACTUAL_WALL_GPU_HOURS_EXCEEDED" in reason
        for reason in evidence["budget_settlement"]["budget_failure_reasons"]
    )
    # The artifact and the measurements are preserved, not rolled back.
    artifact = Path(evidence["artifact_ref"])
    assert (artifact / "payload.safetensors").exists()
    assert Path(evidence["evidence_path"]).exists()
    assert evidence["attempt_row_status"]


def test_a_declared_device_ceiling_is_not_settled_against_an_unmeasured_figure(tmp_path: Path):
    """A wall-only run must not manufacture device compliance.

    The trainer reports wall time; device time stays unseparated. Settlement
    therefore never reads that placeholder as "device free": the ceiling keeps
    its admission teeth against the projected plan, and the evidence says so
    instead of certifying a measurement that never happened.
    """
    runner = _RecordingRunner()  # no device time reported, as in production
    binding = _binding(tmp_path, runner=runner, envelope=_envelope(device_gpu_hours_ceiling=1.0))
    items = _items()

    evidence = binding(_recipe(item_ids=[i.item_id for i in items]), items)

    assert evidence["status"] == STATUS_SUCCEEDED, evidence
    assert evidence["actual_cost"]["device_measured"] is False
    assert evidence["ceiling_enforcement"]["device"] == "admission:projected_plan"
    assert evidence["budget_settlement"]["budget_compliant"] is True
    assert any(
        "device ceiling" in note and "not certified by settlement" in note
        for note in evidence["notes"]
    )


def test_a_measured_device_figure_lets_the_device_ceiling_settle(tmp_path: Path):
    """When a run does separate device time, the ceiling has post-run teeth."""
    # 0.09 device measured by the training leg, ceiling 0.05; the projection
    # (0.01) admitted the recipe, so only the measured cost can refuse it.
    runner = _RecordingRunner(device_gpu_hours=0.09)
    binding = _binding(
        tmp_path, runner=runner, envelope=_envelope(device_gpu_hours_ceiling=0.05)
    )
    items = _items()

    evidence = binding(_recipe(item_ids=[i.item_id for i in items]), items)

    assert evidence["status"] == STATUS_REFUSED
    assert evidence["refused_by"] == "budget_settlement"
    assert evidence["actual_cost"]["device_measured"] is True
    assert evidence["ceiling_enforcement"]["device"] == "settlement:measured"
    assert any(
        "ACTUAL_DEVICE_GPU_HOURS_EXCEEDED" in reason
        for reason in evidence["budget_settlement"]["budget_failure_reasons"]
    )


def test_attempt_directories_are_never_reused(tmp_path: Path):
    """Property 9: a retry is a new attempt, never an in-place rerun."""
    runner = _RecordingRunner()
    binding = _binding(tmp_path, runner=runner)
    items = _items()
    recipe = _recipe(item_ids=[i.item_id for i in items])

    first = binding(recipe, items)
    second = binding(recipe, items)

    assert first["attempt"] == "attempt-01"
    assert second["attempt"] == "attempt-02"
    assert first["attempt_dir"] != second["attempt_dir"]
    # The first attempt's evidence survives the retry untouched.
    recorded = json.loads(Path(first["evidence_path"]).read_text(encoding="utf-8"))
    assert recorded["attempt"] == "attempt-01"


def test_a_colliding_experiment_id_is_refused_instead_of_overwritten(tmp_path: Path):
    """The production registry refuses duplicate ids; the binding must not walk
    into that after doing compute."""
    experiment_id = "growth-ladder-a01"
    runner = _RecordingRunner()
    binding = _binding(tmp_path, runner=runner, registry_path=tmp_path / "runs.db")
    items = _items()
    (tmp_path / "runs.db").touch()
    _seed_registry(tmp_path / "runs.db", experiment_id)

    evidence = binding(_recipe(item_ids=[i.item_id for i in items]), items)

    assert evidence["status"] == "REFUSED"
    assert evidence["refused_by"] == "attempt-identity"
    assert evidence["train_started"] is False


def _seed_registry(path: Path, experiment_id: str) -> None:
    sys.path.insert(0, str(SRC))
    from chowder.models import Experiment, Hypothesis
    from chowder.registry import RunRegistry

    registry = RunRegistry(path)
    try:
        registry.record_experiment(
            Experiment(
                experiment_id=experiment_id,
                parent_id=None,
                hypothesis=Hypothesis(observation="o", suspected_cause="c", intervention="i"),
                config_patch={},
                estimated_gpu_hours=0.1,
            )
        )
    finally:
        registry.close()


def test_the_composed_project_carries_the_recipe_and_never_a_search_section(tmp_path: Path):
    """Property 1 and the plan's honesty rule: the recipe's knobs reach the
    validated config, and no `search` section is invented for a controller that
    has no production caller."""
    runner = _RecordingRunner()
    binding = _binding(tmp_path, runner=runner)
    items = _items()
    recipe = _recipe(item_ids=[i.item_id for i in items], max_steps=7, seq_len=32)

    evidence = binding(recipe, items)

    assert evidence["status"] == "SUCCEEDED", evidence
    composed = json.loads(Path(evidence["project_path"]).read_text(encoding="utf-8"))
    knobs = composed["config"]["backend"]["router_healing"]
    assert knobs["max_steps"] == 7
    assert knobs["seq_len"] == 32
    assert knobs["corpus_path"] == str(Path(evidence["material"]["corpus_path"]))
    assert "search" not in json.dumps(composed)
    assert composed["goal"]["gpu_hour_budget"] == 1.0


def test_the_binding_reports_rather_than_launders_a_stranded_registry_result(tmp_path: Path):
    """Property 9: a result on a non-terminal row fails the attempt.

    The stranded row belongs to *another* experiment than this attempt, which is
    exactly the class the audit exists for: this attempt's own lifecycle is
    clean and complete, so only a registry-wide audit can see the disagreement.
    """
    registry_path = tmp_path / "runs.db"
    registry_path.touch()
    runner = _RecordingRunner()
    binding = _binding(tmp_path, runner=runner, registry_path=registry_path)
    items = _items()

    original = runner._write_run

    def _write_then_strand_a_sibling(cwd: Path, project: Mapping[str, Any]) -> str | None:
        artifact = original(cwd, project)
        sys.path.insert(0, str(SRC))
        from chowder.models import Experiment, ExperimentResult, Hypothesis
        from chowder.registry import RunRegistry

        registry = RunRegistry(Path(project["registry_path"]))
        try:
            registry.record_experiment(
                Experiment(
                    experiment_id="baseline",
                    parent_id=None,
                    hypothesis=Hypothesis(
                        observation="o", suspected_cause="c", intervention="i"
                    ),
                    config_patch={},
                    estimated_gpu_hours=0.1,
                )
            )
            registry.record_result(
                ExperimentResult(
                    experiment_id="baseline",
                    metrics={"holdout_loss": 1.0},
                    gpu_hours=0.0,
                )
            )
            registry.update_experiment_status("baseline", "running")
        finally:
            registry.close()
        return artifact

    runner._write_run = _write_then_strand_a_sibling  # type: ignore[method-assign]
    evidence = binding(_recipe(item_ids=[i.item_id for i in items]), items)

    assert evidence["attempt_row_status"] == "passed", "this attempt's own row is clean"
    assert evidence["status"] == "FAILED"
    assert evidence["registry_audit"], "the stranded sibling row was not reported"
    assert evidence["registry_audit"][0]["experiment_id"] == "baseline"
    assert evidence["registry_audit"][0]["status"] == "running"


def test_evidence_records_the_chowder_source_identity_and_is_json_serializable(tmp_path: Path):
    """Property 6: the run's declared source identity is verified parent-side."""
    runner = _RecordingRunner()
    binding = _binding(tmp_path, runner=runner)
    items = _items()

    evidence = binding(_recipe(item_ids=[i.item_id for i in items]), items)

    assert evidence["status"] == "SUCCEEDED", evidence
    identity = evidence["source_identity"]
    assert identity["verified"] is True
    assert identity["source_sha256"] == _identity_of_this_process()["source_sha256"]
    assert json.loads(json.dumps(evidence))["status"] == "SUCCEEDED"


def test_the_real_runner_child_imports_this_checkout_not_a_competing_one(tmp_path, monkeypatch):
    """Property 6, environmental half: the child runs the code being qualified.

    ``docs`` in ``chowder/worker_env.py`` records the real failure this prevents:
    a worker launched from a worktree silently imported the main checkout's
    ``chowder`` through an editable install, and a run went through the whole
    lifecycle against a different code version than the one under review. The
    identity check below would catch that; not causing it is better.
    """
    decoy = tmp_path / "decoy"
    (decoy / "chowder").mkdir(parents=True)
    (decoy / "chowder" / "__init__.py").write_text("DECOY = True\n", encoding="utf-8")
    monkeypatch.setenv("PYTHONPATH", str(decoy))

    outcome = default_runner(
        [sys.executable, "-c", "import chowder; print(chowder.__file__)"],
        tmp_path,
        {},
        60.0,
    )

    assert outcome.returncode == 0, outcome.stderr
    assert Path(outcome.stdout.strip()).resolve() == (
        SRC / "chowder" / "__init__.py"
    ).resolve(), "the child imported a competing chowder"


def test_a_caller_supplied_pythonpath_is_refused(tmp_path: Path):
    """The binding will not let a caller put a competing checkout first."""
    with pytest.raises(GrowthBindingError, match="PYTHONPATH"):
        SubprocessTrainingFn(
            run_root=tmp_path / "attempts",
            project_template=_template(tmp_path),
            registry_path=tmp_path / "runs.db",
            envelope=_envelope(),
            registry=_admitted_registry(),
            firewall=ContaminationFirewall(),
            environment={"PYTHONPATH": "/somewhere/else"},
        )


def test_a_missing_source_identity_is_a_failure_not_a_pass(tmp_path: Path):
    """Property 6: unknown must not be reported as verified."""
    runner = _RecordingRunner(write_identity=False)
    binding = _binding(tmp_path, runner=runner)
    items = _items()

    evidence = binding(_recipe(item_ids=[i.item_id for i in items]), items)

    assert evidence["status"] == "FAILED"
    assert evidence["source_identity"]["verified"] is False
    assert "identity" in evidence["failure_reason"]


def test_an_unparsable_train_summary_never_becomes_synthetic_metrics(tmp_path: Path):
    """No fabricated evidence: whatever the trainer did not report stays absent."""
    runner = _RecordingRunner(print_summary=False)
    binding = _binding(tmp_path, runner=runner)
    items = _items()

    evidence = binding(_recipe(item_ids=[i.item_id for i in items]), items)

    assert evidence["status"] == "FAILED"
    assert evidence["summary"] is None
    assert evidence["measured_gpu_hours"] is None


# --------------------------------------------------------------------------
# the real layer -- a genuine tiny model through real chowder processes
# --------------------------------------------------------------------------


def _require_real_model() -> None:
    pytest.importorskip("torch")
    pytest.importorskip("transformers")
    pytest.importorskip("safetensors")
    pytest.importorskip("tokenizers")


@pytest.fixture(scope="module")
def tiny_base(tmp_path_factory):
    """A real tiny Qwen3 MoE (E=4, k=2) with a real tokenizer."""
    _require_real_model()
    return _build_tiny_base(tmp_path_factory.mktemp("growth-binding-ladder"))


def _build_tiny_base(root: Path) -> dict[str, Path]:
    import torch
    from tokenizers import Tokenizer, models, pre_tokenizers, trainers
    from transformers import PreTrainedTokenizerFast
    from transformers.models.qwen3_moe import Qwen3MoeConfig, Qwen3MoeForCausalLM

    lines = [
        f"the router selects expert {index % 4} for token number {index} in this sentence"
        for index in range(400)
    ]
    holdout = root / "holdout.txt"
    holdout.write_text(
        "\n".join(
            f"held out sentence {index} asks which expert answers token {index * 3}"
            for index in range(400)
        ),
        encoding="utf-8",
    )

    tokenizer = Tokenizer(models.WordLevel(unk_token="[UNK]"))
    tokenizer.pre_tokenizer = pre_tokenizers.Whitespace()
    tokenizer.train_from_iterator(
        lines, trainers.WordLevelTrainer(vocab_size=64, special_tokens=["[UNK]", "[PAD]"])
    )
    fast = PreTrainedTokenizerFast(
        tokenizer_object=tokenizer, unk_token="[UNK]", pad_token="[UNK]"
    )

    torch.manual_seed(0)
    config = Qwen3MoeConfig(
        vocab_size=64,
        hidden_size=16,
        intermediate_size=8,
        moe_intermediate_size=8,
        num_hidden_layers=2,
        num_attention_heads=2,
        num_key_value_heads=1,
        num_experts=4,
        num_experts_per_tok=2,
        max_position_embeddings=64,
    )
    base = root / "base"
    Qwen3MoeForCausalLM(config).float().save_pretrained(base)
    fast.save_pretrained(base)
    return {"base": base, "holdout": holdout}


def _real_binding(tmp_path: Path, tiny_base, *, template=None, **overrides: Any) -> SubprocessTrainingFn:
    template = template if template is not None else _template(tmp_path)
    knobs = template["config"]["backend"]["router_healing"]
    knobs["base_model_dir"] = str(tiny_base["base"])
    knobs["holdout_corpus_path"] = str(tiny_base["holdout"])
    runner = overrides.pop("runner", None)
    return SubprocessTrainingFn(
        run_root=tmp_path / "attempts",
        project_template=template,
        registry_path=overrides.pop("registry_path", None),
        envelope=overrides.pop("envelope", _envelope()),
        registry=overrides.pop("registry", _admitted_registry()),
        firewall=overrides.pop("firewall", ContaminationFirewall()),
        sources=overrides.pop("sources", None) or {},
        material=overrides.pop("material", None) or {},
        runner=runner,
        python=sys.executable,
        environment={"TOKENIZERS_PARALLELISM": "false"},
        timeout_seconds=overrides.pop("timeout_seconds", 900.0),
        **overrides,
    )


def test_s1_s2_s3_the_binding_drives_real_chowder_processes_end_to_end(tmp_path, tiny_base):
    """S1-S3: real model, real subprocess boundary, real registry.

    Both commands are the production entry points; the rows the registry ends
    with are production rows, audited for the stranded-result class.
    """
    items = _items()
    binding = _real_binding(
        tmp_path,
        tiny_base,
        sources={item.item_id: "src-1" for item in items},
        material=_material(items),
    )
    evidence = binding(_recipe(item_ids=[i.item_id for i in items]), items)
    assert evidence["status"] == "SUCCEEDED", evidence.get("failure_reason") or evidence

    # S2: the process boundary is real, and both commands are the CLI's.
    verbs = [command[-2] for command in evidence["commands"]]
    assert verbs == ["project-validate", "train"], verbs
    assert evidence["validate"]["returncode"] == 0
    assert evidence["train"]["returncode"] == 0

    # S3: production registry rows, terminal, with nothing stranded.
    assert evidence["rows"], "the real run left no registry rows"
    assert all(row["status"] in {"passed", "failed", "rejected"} for row in evidence["rows"])
    assert evidence["registry_audit"] == []
    assert evidence["attempt_row_status"] in {"passed", "failed", "rejected"}
    # The automatic baseline is production's own row, not this binding's.
    assert any(row["experiment_id"] == "baseline" for row in evidence["rows"])

    # Property 6: the identity the run declared matches this parent's code.
    assert evidence["source_identity"]["verified"] is True

    # The trainer's own reported cost and metrics, or nothing at all.
    assert evidence["measured_gpu_hours"] is not None
    assert evidence["measured_gpu_hours"] >= 0.0
    assert evidence["candidate_succeeded"] is True
    assert "holdout_loss" in evidence["candidate_metrics"]

    # The materialized corpus is a real file, recorded by hash.
    corpus = Path(evidence["material"]["corpus_path"])
    assert corpus.exists()
    assert evidence["material"]["corpus_sha256"] == _sha256(corpus)
    assert corpus.read_bytes().count(b"\r") == 0, "the corpus is materialized as LF"

    # S5: the scoring leg is a different process from the training leg.
    kinds = {entry["kind"] for entry in evidence["worker_artifacts"]}
    assert "router_healing_worker_result.v1" in kinds, "no training worker artifact"
    assert "router_healing_eval_result.v1" in kinds, "no separate evaluation worker"
    assert evidence["evaluation"]["outcome_count"] >= 1, (
        "production recorded no independent evaluation outcome"
    )


def _sha256(path: Path) -> str:
    import hashlib

    return hashlib.sha256(path.read_bytes()).hexdigest()


def test_s4_the_real_run_produces_a_reloadable_artifact(tmp_path, tiny_base):
    """S4: an actual artifact exists, its digest is recorded, and it reloads."""
    items = _items()
    binding = _real_binding(
        tmp_path,
        tiny_base,
        sources={item.item_id: "src-1" for item in items},
        material=_material(items),
    )
    evidence = binding(_recipe(item_ids=[i.item_id for i in items]), items)
    assert evidence["status"] == "SUCCEEDED", evidence.get("failure_reason") or evidence

    artifact_ref = evidence["artifact_ref"]
    assert artifact_ref, "a succeeded run must name its artifact"
    assert evidence["artifact_sha256"], "the artifact digest must be recorded"

    # The recorded digest is of real files, and the artifact reloads key-for-key
    # in this process from the recorded reference alone.
    assert evidence["artifact_files"], "the artifact digest covered no files"
    for entry in evidence["artifact_files"]:
        assert (Path(artifact_ref) / entry["path"]).is_file()

    sys.path.insert(0, str(SRC))
    from chowder.router_payload import load_router_payload

    manifest = json.loads(
        (Path(artifact_ref) / "router_payload.json").read_text(encoding="utf-8")
    )
    payload = load_router_payload(
        artifact_ref,
        expected_base_content_sha256=manifest["base_content_sha256"],
    )
    assert payload["tensors"], "the reloaded payload carries no tensors"
    assert manifest["steps_completed"] == 4


def test_s7_the_growth_cycle_itself_drives_real_training(tmp_path, tiny_base):
    """The claim under test: the loop, not just the binding, trains.

    A ``GrowthCycle`` handed this binding runs its own training phase against
    two competing recipes, and the evidence it returns is the run's own: real
    registry rows, real measured cost, real metrics, each attempt in its own
    directory. Promotion stays where it was -- ``evaluate_promotion`` on
    benchmark measurements -- and is not invented here from a training loss.
    """
    items = _items()
    binding = _real_binding(
        tmp_path,
        tiny_base,
        sources={item.item_id: "src-1" for item in items},
        material=_material(items),
    )
    cycle = _cycle(tmp_path, binding)
    recipes = (
        _recipe(recipe_id="recipe-00", max_steps=4, item_ids=[i.item_id for i in items]),
        _recipe(recipe_id="recipe-01", max_steps=6, item_ids=[i.item_id for i in items]),
    )

    results = cycle.train_candidates(items, recipes)

    assert [row["recipe_id"] for row in results] == ["recipe-00", "recipe-01"]
    assert [row["status"] for row in results] == ["SUCCEEDED", "SUCCEEDED"], results
    assert results[0]["attempt_dir"] != results[1]["attempt_dir"]
    for row, recipe in zip(results, recipes):
        assert row["measured_gpu_hours"] is not None
        assert row["candidate_succeeded"] is True
        assert row["attempt_row_status"] in {"passed", "failed", "rejected"}
        assert row["projected_device_gpu_hours"] == recipe.projected_device_gpu_hours
        # The recipe the cycle ran is the recipe the project was composed from.
        composed = json.loads(Path(row["project_path"]).read_text(encoding="utf-8"))
        assert composed["config"]["backend"]["router_healing"]["max_steps"] == recipe.max_steps

    # Each attempt carries its own production registry, its own automatic
    # baseline and its own audit: rows terminal, nothing stranded, and no attempt
    # reading another attempt's rows.
    sys.path.insert(0, str(SRC))
    from chowder.registry import RunRegistry

    for row in results:
        registry = RunRegistry(Path(row["registry_path"]))
        try:
            rows = {
                experiment.experiment_id: experiment.status.value
                for experiment in registry.list_experiments()
            }
            assert registry.audit_stranded_results() == []
        finally:
            registry.close()
        assert sorted(rows) == ["baseline", row["experiment_id"]], rows
        assert all(status in {"passed", "failed", "rejected"} for status in rows.values())
    assert results[0]["registry_path"] != results[1]["registry_path"]


def test_a_shared_registry_cannot_re_establish_an_automatic_baseline(tmp_path: Path):
    """The production constraint the ladder found, named instead of crashed.

    Production's automatic baseline writes an experiment literally named
    ``baseline`` and the registry refuses a duplicate id, so a registry holds
    exactly one automatic baseline. A second attempt against the same registry
    must be refused here -- with the constraint in the reason -- rather than
    inside a child traceback after a model load.
    """
    shared = tmp_path / "runs.db"
    shared.touch()
    _seed_registry(shared, "baseline")
    runner = _RecordingRunner()
    binding = _binding(tmp_path, runner=runner, registry_path=shared)
    items = _items()

    evidence = binding(_recipe(item_ids=[i.item_id for i in items]), items)

    assert evidence["status"] == "REFUSED"
    assert evidence["refused_by"] == "registry-baseline"
    assert "duplicate" in evidence["refusal_reason"]
    assert "baseline.mode='fixed'" in evidence["refusal_reason"]
    assert evidence["train_started"] is False
    assert runner.commands == []

    # The same shared registry accepts a project that does not establish its own.
    fixed = _template(tmp_path)
    fixed["baseline"] = {"mode": "fixed", "metrics": {"holdout_loss": 4.0}}
    allowed = _binding(
        tmp_path / "fixed", runner=_RecordingRunner(), registry_path=shared, template=fixed
    )
    assert allowed(_recipe(item_ids=[i.item_id for i in items]), items)["status"] == "SUCCEEDED"


def test_s6_every_refusal_refuses_before_any_trainer_starts(tmp_path, tiny_base):
    """S6: invalid config, over-budget recipe and contaminated material.

    Three refusals through the real template against the real validator. None of
    them may start a trainer, and each must leave terminal evidence.
    """
    items = _items()
    sources = {item.item_id: "src-1" for item in items}
    recipe = _recipe(item_ids=[i.item_id for i in items])

    # (a) a goal metric nothing measures: the real validator refuses it.
    template = _template(tmp_path)
    template["goal"]["metrics"].append({"name": "gsm8k", "direction": "maximize"})
    validator_case = _real_binding(
        tmp_path / "invalid-project", tiny_base, template=template,
        sources=sources, material=_material(items),
    )
    evidence = validator_case(recipe, items)
    assert evidence["refused_by"] == "project-validate", evidence
    assert evidence["train_started"] is False
    assert [command[-2] for command in evidence["commands"]] == ["project-validate"]
    assert "not measured by the router-healing" in Path(
        evidence["validate"]["stderr_ref"]
    ).read_text(encoding="utf-8")
    assert json.loads(Path(evidence["evidence_path"]).read_text(encoding="utf-8"))[
        "status"
    ] == "REFUSED"

    # (b) a recipe over the growth envelope: no process at all.
    over_budget = _real_binding(
        tmp_path / "over-budget", tiny_base, sources=sources,
        material=_material(items),
        envelope=GrowthEnvelope(
            device_gpu_hours_ceiling=0.0, wall_gpu_hours_ceiling=0.0,
            project_gpu_hour_budget=1.0,
        ),
    )
    evidence = over_budget(recipe, items)
    assert evidence["refused_by"] == "growth-envelope"
    assert evidence["commands"] == []
    assert Path(evidence["evidence_path"]).exists()

    # (c) protected evaluation material offered as training text: no process at all.
    protected = "what is the exact protected question number seven answer"
    firewall = ContaminationFirewall()
    firewall.register_protected(PROTECTED_ID, [protected])
    tainted_material = _material(items)
    tainted_material[items[0].item_id] = [protected]
    tainted = _real_binding(
        tmp_path / "tainted", tiny_base, sources=sources,
        material=tainted_material, firewall=firewall,
    )
    evidence = tainted(recipe, items)
    assert evidence["refused_by"] == "contamination-firewall"
    assert evidence["commands"] == []
    assert Path(evidence["evidence_path"]).exists()
