"""Production Kaggle transport: push, poll, pull and quota over the CLI.

Implements the :class:`chowder.growth.kaggle_compute.KaggleTransport` protocol
so :class:`~chowder.growth.kaggle_compute.KaggleComputeBackend` can dispatch
kernels for real. The transport:

* stages a kernel folder from the :class:`KaggleJobSpec` -- the generated
  entry script, the job document (declared inputs, mounts, commit, payload
  command) and ``kernel-metadata.json`` (private, GPU, declared mounts);
* pushes it with the declared timeout, because every kernel second is
  charged to the weekly quota whether or not it produces anything;
* polls ``kaggle kernels status`` to a terminal state under
  timeout + grace, with injected clock and sleep so the loop is testable;
* pulls the output, reads the kernel's ``job-record.json``, copies the
  pulled artifacts into the attempt's destination, and returns the
  :class:`KaggleJobRecord` the backend then verifies (commit echo, input
  digests, manifest, environment, settlement);
* reads ``kaggle quota`` before dispatch, parsed into remaining GPU hours.

Every CLI call goes through an injectable ``runner`` and every operational
failure is a :class:`KaggleTransportError`: the backend classifies it as an
INFRASTRUCTURE attempt failure with the cause attached. The transport never
reads, logs or copies Kaggle credentials, never retries silently, and never
fabricates a record.

The platform log and the kernel's own record are pulled into a sibling
``<destination>-kaggle-output`` directory for the audit; only the kernel's
artifacts are copied into the attempt destination, so the manifest check
sees exactly the files the kernel claims to have emitted.
"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
import subprocess
import tempfile
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Mapping, Sequence

from .compute_backend import ArtifactEntry, ComputeBackendRefusal
from .kaggle_compute import (
    KaggleJobRecord,
    KaggleJobSpec,
    KaggleQuota,
    KaggleTransportError,
)
from .kaggle_kernel import (
    JOB_RECORD_NAME,
    KERNEL_JOB_SPEC_NAME,
    RESUME_STATES,
    install_spec,
)

__all__ = [
    "KAGGLE_CLI_NAME",
    "KERNEL_ENTRY_NAME",
    "KERNEL_ENTRY_SOURCE",
    "DEFAULT_MACHINE_SHAPES",
    "KaggleCliTransport",
    "kernel_slug",
    "machine_shape",
    "parse_quota",
    "parse_status",
]

Runner = Callable[[Sequence[str]], "subprocess.CompletedProcess[str]"]

KAGGLE_CLI_NAME = "kaggle"
KERNEL_ENTRY_NAME = "kernel_entry.py"

#: Kaggle ``machine_shape`` values, keyed by the shape names the declared
#: accelerators use. Only shapes the repo can map honestly appear here; a
#: shape without a mapping refuses rather than running on different hardware
#: than the campaign priced.
DEFAULT_MACHINE_SHAPES: Mapping[str, str] = {
    "T4x2": "NvidiaTeslaT4",
}

TERMINAL_OK = "complete"
TERMINAL_FAILED = frozenset(
    {"error", "cancelacknowledged", "cancelrequested", "cancelled"}
)
_RUNNING = frozenset({"queued", "running", "new"})

_SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9-]{3,48}[a-z0-9]$")
_STATUS_RE = re.compile(r"status[\s:=]+[\"']?([A-Za-z_.]+)", re.IGNORECASE)
_ENUM_STATUS_RE = re.compile(r"KernelWorkerStatus\.([A-Za-z_]+)")

_QUOTA_PATTERNS: tuple[tuple[re.Pattern[str], str], ...] = (
    (re.compile(r"remaining[:\s]+(\d+(?:\.\d+)?)\s*(?:gpu\s*)?(?:hours?|h)\b", re.I), "hours"),
    (re.compile(r"(\d+(?:\.\d+)?)\s*(?:gpu\s*)?(?:hours?|h)\b\s*(?:remaining|left)", re.I), "hours"),
    (re.compile(r"(\d+)\s*h(?:ours?)?\s+(\d+)\s*m(?:inutes?)?\s*(?:remaining|left)", re.I), "hours_minutes"),
)

#: The generated kernel entry script. It is deliberately self-contained for
#: the install step (the pinned package cannot be imported before it is
#: installed) and delegates everything else to the installed package's
#: ``chowder.growth.kaggle_kernel.run_kernel_job``, so the verification logic
#: is versioned, reviewed and unit-tested rather than duplicated in a
#: generated blob. A failure before the package is importable still writes a
#: minimal error record -- a failed attempt without evidence is a dropped
#: failure.
KERNEL_ENTRY_SOURCE = '''"""Chowder Kaggle kernel entry point. Generated by chowder.growth.kaggle_cli_transport."""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

SPEC_PATH = Path(__file__).with_name("chowder-job-spec.json")


def write_record(
    output_dir: str,
    state: str,
    commit: str,
    error: str,
    spec: dict | None = None,
) -> None:
    """Write the job record; identity comes from the job document, never invented."""
    spec = spec or {}
    resume_from = spec.get("resume_from")
    record = {
        "spec_id": str(spec.get("spec_id") or ""),
        "state": state,
        "source_commit_sha": commit,
        "input_verification": [],
        "artifact_manifest": [],
        "environment": {},
        "mounts": [str(mount) for mount in (spec.get("mounts") or [])],
        "resume_from": resume_from,
        "resume_state": "not-a-resume" if resume_from else None,
        "command": None,
        "error": error,
    }
    path = Path(output_dir) / "job-record.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(record, indent=2, sort_keys=True) + "\\n",
        encoding="utf-8",
    )


def main() -> int:
    document = json.loads(SPEC_PATH.read_text(encoding="utf-8"))
    spec = document.get("spec") or {}
    kernel = document["kernel"]
    output_dir = kernel.get("output_dir") or "/kaggle/working"
    if not kernel.get("skip_install"):
        completed = subprocess.run(
            [sys.executable, "-m", "pip", "install", "--quiet", kernel["install_spec"]],
            capture_output=True,
            text=True,
        )
        if completed.returncode != 0:
            write_record(
                output_dir,
                "error",
                "",
                "installing the pinned source failed: "
                + (completed.stderr or completed.stdout or "").strip()[-2000:],
                spec,
            )
            return 1
    try:
        from chowder.growth.kaggle_kernel import run_kernel_job
    except Exception as exc:
        write_record(
            output_dir,
            "error",
            "",
            "the installed chowder package cannot be imported: " + str(exc),
            spec,
        )
        return 1

    record = run_kernel_job(document)
    return 0 if record["state"] == "complete" else 1


if __name__ == "__main__":
    raise SystemExit(main())
'''


def default_runner(args: Sequence[str]) -> "subprocess.CompletedProcess[str]":
    """Run one CLI command; the default runner never touches a shell."""
    return subprocess.run(list(args), capture_output=True, text=True, timeout=600)


def parse_status(stdout: str) -> str:
    """The kernel state from ``kaggle kernels status`` output, normalized.

    Accepts both the human form (``has status "complete"``) and the enum form
    (``KernelWorkerStatus.COMPLETE``); anything unrecognised refuses, because
    an unreadable status is not a licence to keep polling forever.
    """
    match = _STATUS_RE.search(stdout)
    raw = match.group(1) if match else None
    if raw is None:
        fallback = _ENUM_STATUS_RE.search(stdout)
        raw = fallback.group(1) if fallback else None
    if raw is None:
        raise KaggleTransportError(
            f"unrecognised `kaggle kernels status` output: {stdout.strip()[-500:]!r}"
        )
    return raw.split(".")[-1].lower()


def parse_quota(stdout: str) -> KaggleQuota:
    """The remaining weekly GPU balance from ``kaggle quota`` output.

    The CLI's wording is plain English and has changed before, so several
    documented forms are accepted; an unparseable balance refuses rather than
    guessing a number, because a guessed quota is an unpriced dispatch.
    """
    text = stdout.strip()
    if not text:
        raise KaggleTransportError("`kaggle quota` printed nothing")
    for pattern, kind in _QUOTA_PATTERNS:
        match = pattern.search(text)
        if match is None:
            continue
        groups = match.groups()
        if kind == "hours_minutes":
            hours = float(groups[0]) + float(groups[1]) / 60.0
        else:
            hours = float(groups[0])
        return KaggleQuota(remaining_gpu_hours=hours, raw=text)
    raise KaggleTransportError(
        "could not parse a remaining GPU balance from `kaggle quota` output: "
        f"{text[-500:]!r}"
    )


def machine_shape(accelerator: str, shapes: Mapping[str, str]) -> str:
    """The CLI ``machine_shape`` for a declared accelerator, or a refusal."""
    shape = shapes.get(str(accelerator))
    if not shape:
        raise KaggleTransportError(
            f"the declared accelerator {accelerator!r} has no Kaggle machine_shape "
            f"mapping; known: {sorted(shapes)}. Dispatching it would run on "
            "hardware the campaign did not price"
        )
    return shape


def kernel_slug(spec_id: str, commit_sha: str, prefix: str) -> str:
    """A valid, unique, deterministic kernel slug for one attempt."""
    base = re.sub(r"[^a-z0-9]+", "-", str(spec_id).lower()).strip("-")[:32].strip("-")
    digest = hashlib.sha256(f"{spec_id}:{commit_sha}".encode("utf-8")).hexdigest()[:8]
    slug = f"{prefix}-{base}-{digest}" if base else f"{prefix}-{digest}"
    slug = slug[:49].rstrip("-")
    if not _SLUG_RE.match(slug):
        raise KaggleTransportError(
            f"derived kernel slug {slug!r} is not a valid Kaggle kernel id "
            "(5-50 chars of [a-z0-9-], starting and ending alphanumeric)"
        )
    return slug


@dataclass
class KaggleCliTransport:
    """The official ``kaggle`` CLI behind the transport protocol."""

    owner: str
    runner: Runner = default_runner
    poll_seconds: float = 30.0
    poll_grace_seconds: float = 900.0
    command: tuple[str, ...] = (KAGGLE_CLI_NAME,)
    machine_shapes: Mapping[str, str] = field(
        default_factory=lambda: dict(DEFAULT_MACHINE_SHAPES)
    )
    staging_root: Path | None = None
    clock: Callable[[], float] = time.time
    sleep: Callable[[float], None] = time.sleep

    def __post_init__(self) -> None:
        if not str(self.owner).strip():
            raise KaggleTransportError("owner must be the Kaggle username the CLI is authenticated as")
        if self.poll_seconds <= 0.0:
            raise KaggleTransportError("poll_seconds must be positive")
        if self.poll_grace_seconds < 0.0:
            raise KaggleTransportError("poll_grace_seconds cannot be negative")
        if not self.command:
            raise KaggleTransportError("command must name the kaggle executable")

    # ------------------------------------------------------------------
    # the KaggleTransport protocol
    # ------------------------------------------------------------------

    def quota(self) -> KaggleQuota:
        return parse_quota(self._kaggle("quota"))

    def run(self, spec: KaggleJobSpec, destination: Path) -> KaggleJobRecord:
        destination = Path(destination)
        if destination.exists() and any(destination.iterdir()):
            raise KaggleTransportError(
                f"destination {destination} is not fresh; an attempt's output "
                "never shares a directory with another attempt"
            )
        destination.mkdir(parents=True, exist_ok=True)

        slug = kernel_slug(spec.spec_id, spec.source.commit_sha, "chowder")
        kernel_ref = f"{self.owner}/{slug}"
        staging_root = (
            Path(self.staging_root)
            if self.staging_root is not None
            else Path(tempfile.mkdtemp(prefix="chowder-kaggle-"))
        )
        kernel_dir = staging_root / slug
        self._stage(spec, kernel_dir, slug, kernel_ref)

        pushed_at = self.clock()
        self._kaggle(
            "kernels",
            "push",
            "-p",
            str(kernel_dir),
            "-t",
            str(int(spec.timeout_seconds)),
            "--accelerator",
            machine_shape(spec.accelerator, self.machine_shapes),
        )
        state, status_text = self._wait(kernel_ref, pushed_at, spec.timeout_seconds)

        raw_output = destination.parent / f"{destination.name}-kaggle-output"
        if raw_output.exists():
            shutil.rmtree(raw_output)
        raw_output.mkdir(parents=True, exist_ok=True)
        self._kaggle("kernels", "output", kernel_ref, "-p", str(raw_output), "-o", "-q")
        finished_at = self.clock()
        wall_seconds = max(0.0, finished_at - pushed_at)

        record_path = raw_output / JOB_RECORD_NAME
        if not record_path.is_file():
            raise KaggleTransportError(
                f"kernel {kernel_ref} ended {state!r} without writing "
                f"{JOB_RECORD_NAME}; platform log tail: "
                f"{self._log_tail(kernel_ref) or '<unavailable>'}"
            )
        try:
            document = json.loads(record_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise KaggleTransportError(
                f"the job record {record_path} cannot be read: {exc}"
            ) from exc
        if not isinstance(document, Mapping):
            raise KaggleTransportError(f"the job record {record_path} is not a JSON object")

        self._copy_artifacts(raw_output, destination)
        record = self._record_from_document(
            kernel_ref, spec, document, state, status_text, wall_seconds
        )
        return record

    # ------------------------------------------------------------------
    # staging and parsing
    # ------------------------------------------------------------------

    def _kaggle(self, *args: str) -> str:
        argv = [*self.command, *args]
        try:
            result = self.runner(argv)
        except FileNotFoundError as exc:
            raise KaggleTransportError(
                f"the kaggle CLI was not found ({exc}); install the official "
                "`kaggle` package and authenticate it before dispatching"
            ) from exc
        except Exception as exc:
            raise KaggleTransportError(
                f"`{' '.join(argv)}` could not run: {exc}"
            ) from exc
        if result.returncode != 0:
            raise KaggleTransportError(
                f"`{' '.join(argv)}` exited {result.returncode}: "
                f"{(result.stderr or result.stdout or '').strip()[-2000:]}"
            )
        return result.stdout or ""

    def _stage(self, spec: KaggleJobSpec, kernel_dir: Path, slug: str, kernel_ref: str) -> None:
        if kernel_dir.exists():
            shutil.rmtree(kernel_dir)
        kernel_dir.mkdir(parents=True)
        (kernel_dir / KERNEL_ENTRY_NAME).write_text(KERNEL_ENTRY_SOURCE, encoding="utf-8")

        payload = dict(spec.payload)
        extras = payload.get("pip_extras") or ["train"]
        document = {
            "spec": spec.to_dict(),
            "kernel": {
                "kernel_ref": kernel_ref,
                "slug": slug,
                "install_spec": install_spec(
                    spec.source.repository,
                    spec.source.commit_sha,
                    extras=tuple(str(extra) for extra in extras),
                ),
                "command": list(payload.get("command") or []),
                "input_paths": dict(payload.get("input_paths") or {}),
                "output_dir": str(payload.get("output_dir") or "/kaggle/working"),
                "model_commit": payload.get("model_commit"),
                "skip_install": bool(payload.get("skip_install", False)),
            },
        }
        (kernel_dir / KERNEL_JOB_SPEC_NAME).write_text(
            json.dumps(document, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        metadata = {
            "id": kernel_ref,
            "title": slug.replace("-", " ").title()[:50],
            "code_file": KERNEL_ENTRY_NAME,
            "language": "python",
            "kernel_type": "script",
            "is_private": True,
            "enable_gpu": True,
            "enable_internet": True,
            "machine_shape": machine_shape(spec.accelerator, self.machine_shapes),
            "dataset_sources": list(spec.mounts),
            "competition_sources": [],
            "model_sources": [],
        }
        (kernel_dir / "kernel-metadata.json").write_text(
            json.dumps(metadata, indent=2) + "\n", encoding="utf-8"
        )

    def _wait(
        self, kernel_ref: str, pushed_at: float, timeout_seconds: float
    ) -> tuple[str, str]:
        deadline = pushed_at + float(timeout_seconds) + self.poll_grace_seconds
        while True:
            stdout = self._kaggle("kernels", "status", kernel_ref)
            state = parse_status(stdout)
            if state == TERMINAL_OK or state in TERMINAL_FAILED:
                return state, stdout.strip()
            if state not in _RUNNING:
                raise KaggleTransportError(
                    f"unexpected kernel status {state!r} for {kernel_ref}"
                )
            if self.clock() > deadline:
                raise KaggleTransportError(
                    f"kernel {kernel_ref} was still {state!r} past "
                    "timeout + grace; the charged session is not waiting forever"
                )
            self.sleep(self.poll_seconds)

    def _log_tail(self, kernel_ref: str, limit: int = 2000) -> str:
        try:
            return self._kaggle("kernels", "logs", kernel_ref).strip()[-limit:]
        except KaggleTransportError:
            return ""

    def _copy_artifacts(self, raw_output: Path, destination: Path) -> None:
        """Copy the kernel's artifacts, never its record or platform log."""
        for path in sorted(raw_output.rglob("*")):
            if not path.is_file():
                continue
            relative = path.relative_to(raw_output).as_posix()
            if (
                relative == JOB_RECORD_NAME
                or relative.endswith(".log")
                or "__pycache__" in path.parts
                or relative.endswith((".pyc", ".pyo"))
            ):
                continue
            target = destination / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(path, target)

    def _record_from_document(
        self,
        kernel_ref: str,
        spec: KaggleJobSpec,
        document: Mapping,
        cli_state: str,
        status_text: str,
        wall_seconds: float,
    ) -> KaggleJobRecord:
        state = str(document.get("state") or "error")
        error = str(document.get("error") or "")
        if cli_state != TERMINAL_OK and state == "complete":
            state = "error"
            error = (
                f"the CLI reported {cli_state!r} while the kernel record claimed "
                f"complete; the platform state wins ({status_text[-300:]})"
            )
        try:
            input_verification = tuple(
                tuple(str(part) for part in pair)
                for pair in (document.get("input_verification") or [])
            )
            artifact_manifest = tuple(
                ArtifactEntry(
                    path=str(entry["path"]),
                    sha256=str(entry["sha256"]),
                    bytes=int(entry["bytes"]),
                )
                for entry in (document.get("artifact_manifest") or [])
            )
        except (KeyError, TypeError, ValueError, ComputeBackendRefusal) as exc:
            raise KaggleTransportError(
                f"the kernel record from {kernel_ref} carries a malformed "
                f"manifest: {exc}"
            ) from exc
        resume_state = document.get("resume_state")
        if resume_state is not None and resume_state not in RESUME_STATES:
            raise KaggleTransportError(
                f"the kernel record from {kernel_ref} reports resume_state "
                f"{resume_state!r}, which is not one of {RESUME_STATES}"
            )
        return KaggleJobRecord(
            job_id=kernel_ref,
            state=state,
            wall_seconds=wall_seconds,
            accelerator=spec.accelerator,
            source_commit_sha=str(document.get("source_commit_sha") or ""),
            input_verification=input_verification,
            artifact_manifest=artifact_manifest,
            environment=dict(document.get("environment") or {}),
            resume_state=resume_state if resume_state is None else str(resume_state),
            resume_from=document.get("resume_from"),
            mounts=tuple(str(mount) for mount in (document.get("mounts") or ())),
            error=error,
        )
